//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpMaster()
        {
            this.SalaryInfoes = new HashSet<SalaryInfo>();
        }
    
        public int EmpCode { get; set; }
        public string EmpName { get; set; }
        public System.DateTime EmpDob { get; set; }
        public string Email { get; set; }
        public string EmpDepartment { get; set; }
        public string EmpDesignation { get; set; }
    
        public virtual DepartmentMaster DepartmentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryInfo> SalaryInfoes { get; set; }
    }
}
